config/routes.rb
Rails.application.routes.draw do
  resources :empleados

  get :'/pagina_error', to: "documents#pagina_error"

  get :reporte_pdf, to: "documents#reporte_pdf"
  root  "empleados#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/empleado.rb
class Empleado < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

  def reporte_pdf
    begin
      @empleados = Empleado.all

        if @empleados.count <=0
        else
          respond_to do |format|
          format.html
          format.pdf do
          pdf = Reporte.new(@empleados)
          send_data pdf.render, filename:"reporte.pdf",
          type: "application/pdf",
          disposition: "inline"
        end
      end
    end
    rescue Exception => e
      NotificacionMailer.aviso(e.message,e.backtrace.inspect).deliver
      redirect_to '/pagina_error'
    end
  end

  def pagina_error

  end

end

app/controllers/empleados_controller.rb
class EmpleadosController < ApplicationController
  before_action :set_empleado, only: [:show, :edit, :update, :destroy]

  def index
    begin
      @empleados = Empleado.all
    rescue Exception => e
    NotificacionMailer.aviso(e.message,e.backtrace.inspect).deliver
    redirect_to '/pagina_error'
    end
  end

  def show
  end

  def new
    begin
    @empleado = Empleado.new
  rescue Exception => e
    NotificacionMailer.aviso(e.message,e.backtrace.inspect).deliver
    redirect_to '/pagina_error'
    end
  end

  def edit
  end

  def create
    begin
    @empleado = Empleado.new(empleado_params)
    respond_to do |format|
      if @empleado.save
        format.html { redirect_to @empleado, notice: 'Empleado se creo con exito.' }
        format.json { render :show, status: :created, location: @empleado }
      else
        format.html { render :new }
        format.json { render json: @empleado.errors, status: :unprocessable_entity }
      end
    end
  rescue Exception => e
    NotificacionMailer.aviso(e.message,e.backtrace.inspect).deliver
    redirect_to '/pagina_error'
    end
  end

  def update
    begin
    respond_to do |format|
      if @empleado.update(empleado_params)
        format.html { redirect_to @empleado, notice: 'Empleado se actualizo con exito.' }
        format.json { render :show, status: :ok, location: @empleado }
      else
        format.html { render :edit }
        format.json { render json: @empleado.errors, status: :unprocessable_entity }
      end
    end
  rescue Exception => e
    NotificacionMailer.aviso(e.message,e.backtrace.inspect).deliver
    redirect_to '/pagina_error'
    end
  end

  def destroy
    begin
    @empleado.destroy
    respond_to do |format|
      format.html { redirect_to empleados_url, notice: 'Empleado se elimino con exito.' }
      format.json { head :no_content }
    end
  rescue Exception => e
    NotificacionMailer.aviso(e.message,e.backtrace.inspect).deliver
    redirect_to '/pagina_error'
    end
  end

  private
    def set_empleado
      begin
      @empleado = Empleado.find(params[:id])
    rescue Exception => e
    NotificacionMailer.aviso(e.message,e.backtrace.inspect).deliver
    redirect_to '/pagina_error'
  end
    end

    def empleado_params
      begin
      params.require(:empleado).permit(:strnombre, :strapellidopaterno, :strapellidomaterno, :dtefechanacimiento)
    rescue Exception => e
          NotificacionMailer.aviso(e.message,e.backtrace.inspect).deliver
          redirect_to '/pagina_error'
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/views/documents/pagina_error.html.erb
<!DOCTYPE html>
<html lang=&quot;es&quot;>
     <head>
		<meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; />
		<meta name=&quot;description&quot; content=&quot;Esta Tienda está desarrollada con PrestaShop&quot; />
        <style>
            ::-moz-selection {background: #b3d4fc; text-shadow: none;}
            ::selection {background: #b3d4fc; text-shadow: none;}
            html {padding: 30px 10px; font-size: 16px; line-height: 1.4; color: #737373; background: #f0f0f0;
                -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%;}
            html,
            input {font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;}
            body {max-width:700px; _width: 700px; padding: 30px 20px 50px; border: 1px solid #b3b3b3;
                border-radius: 4px;margin: 0 auto; box-shadow: 0 1px 10px #a7a7a7, inset 0 1px 0 #fff;
                background: #fcfcfc;}
            h1 {margin: 0 10px; font-size: 50px; text-align: center;}
            h1 span {color: #bbb;}
            h2 {color: #D35780;margin: 0 10px;font-size: 40px;text-align: center;}
            h2 span {color: #bbb;font-size: 80px;}
            h3 {margin: 1.5em 0 0.5em;}
            p {margin: 1em 0;}
            ul {padding: 0 0 0 40px;margin: 1em 0;}
            .container {max-width: 380px;_width: 480px;margin: 0 auto;}
            input::-moz-focus-inner {padding: 0;border: 0;}
        </style>
    </head>
    <body>
        <div class=&quot;container&quot;>
            <h2><span>500</span>Error interno del servidor</h2>
            <p>¡Vaya! Algo salió mal.<br /><br />Trata de volver a cargar esta página o no dudes en contactar con nosotros si el problema persiste.</p>
        </div>
    </body>
</html>

app/views/empleados/_form.html.erb
<div class="form-group">
<%= form_with(model: empleado, local: true) do |form| %>
  <% if empleado.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% empleado.errors.messages.each do |message| %>
            <li><%= message.last.last.html_safe %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :Nombre %>
    <%= form.text_field :strnombre, class:'form-control'  %>
  </div>
  <div class="field">
    <%= form.label :Apellido_Paterno %>
    <%= form.text_field :strapellidopaterno, class:'form-control'  %>
  </div>
  <div class="field">
    <%= form.label :Apellido_Materno %>
    <%= form.text_field :strapellidomaterno, class:'form-control'  %>
  </div>
  <div class="field">
    <%= form.label :Fecha_Nacimiento %><br>
    <%= form.date_select :dtefechanacimiento, class:'form-control',start_year: Date.current.year, end_year: Date.current.year - 333 %>
  </div>
<br>
  <div class="actions">
    <%= form.submit:Guardar,class:'btn btn-info' %>
  </div>
<% end %>
</div>

app/views/empleados/edit.html.erb
<div class="container" style="width:50%">
<h1 align="center">Editar Empleado</h1>

<%= render 'form', empleado: @empleado %>

<%= link_to 'Visualizar', @empleado %> |
<%= link_to 'Cancelar', empleados_path %>
</div>

app/views/empleados/index.html.erb
<div class="col-12">
<p style="text-aling:center" id="notice"><%= notice %></p>
<h1 style="text-aling:center" align="center">Empleados</h1>
<br>
<%= link_to 'Agregar Empleado', new_empleado_path %>
<br><br>
<%= link_to "Generar PDF", reporte_pdf_path(:format => :pdf) %>
<br><br>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Nombre</th>
      <th scope="col">Apellido Paterno</th>
      <th scope="col">Apellido Materno</th>
      <th scope="col">Fecha Nacimiento</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @empleados.each do |empleado| %>
      <tr>
        <td><%= empleado.strnombre %></td>
        <td><%= empleado.strapellidopaterno %></td>
        <td><%= empleado.strapellidomaterno %></td>
        <td><%= empleado.dtefechanacimiento %></td>
        <td><%= link_to 'Visualizar', empleado %></td>
        <td><%= link_to 'Editar', edit_empleado_path(empleado) %></td>
        <td><%= link_to 'Eliminar', empleado, method: :delete, data: { confirm: '¿Desea eliminar el registro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/empleados/new.html.erb
<div class="container" style="width:50%">
<h1 align="center">Nuevo Empleado</h1>

<%= render 'form', empleado: @empleado %>

<%= link_to 'Cancelar', empleados_path %>
</div>

app/views/empleados/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
<h1>Empleado</h1>

<p>
  <strong>Nombre:</strong>
  <%= @empleado.strnombre %>
</p>

<p>
  <strong>Apellido Paterno:</strong>
  <%= @empleado.strapellidopaterno %>
</p>

<p>
  <strong>Apellido Materno:</strong>
  <%= @empleado.strapellidomaterno %>
</p>

<p>
  <strong>Fecha Nacimiento:</strong>
  <%= @empleado.dtefechanacimiento %>
</p>

<%= link_to 'Editar', edit_empleado_path(@empleado) %> |
<%= link_to 'Cancelar', empleados_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProyectoEmpleado</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>